#!/data/data/com.termux/files/usr/bin/env bash
shopt -s expand_aliases
alias ee='echo -e'
ee "\e[93mThis script will install Java in Termux."
ee "\e[93mLibraries compiled by \e[32mHax4us\e[93m, script written by \e[32mHax4us 
\e[93mAnd small patch for tmp file by \e[32mRemo773\e[93m."
echo
if [ -e $PREFIX/bin/java ]
then
	ee "\e[32mJava is already installed!"
	echo
	exit
else
	case `dpkg --print-architecture` in
	aarch64)
		archname="aarch64" ;;
	arm64)
		archname="aarch64" ;;
	armhf)
		archname="arm" ;;
	armv7l)
		archname="arm" ;;
	arm)
		archname="arm" ;;
	*)
		ee "\e[91mERROR: Unknown architecture."; echo; exit ;;
	esac
	ee "\e[32m[*] \e[34mDownloading JDK-8 (~70Mb) for ${archname}..."
	(axel --insecure --alternate "https://archive.org/download/openjdk-9-jre-headless_9.2017.8.20-1_arm/jdk8_${archname}.tar.gz") &> /dev/null;
	ee "\e[32m[*] \e[34mMoving JDK to system..."
	mv jdk8_${archname}.tar.gz $PREFIX/share
	ee "\e[32m[*] \e[34mExtracting JDK..."
	cd $PREFIX/share
	tar -xhf jdk8_${archname}.tar.gz
	ee "\e[32m[*] \e[34mMoving Java wrapper scripts to bin..."
	mv bin/* $PREFIX/bin
	ee "\e[32m[*] \e[34mCleaning up temporary files..."
	rm -rf installjava
	rm -rf $PREFIX/share/jdk8_${archname}.tar.gz
	rm -rf $PREFIX/share/bin
	echo
	ee "\e[32mJava was successfully installed!\e[39m"
	echo
 fi
